# render.yaml

services:
  - name: web
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn todo.wsgi:application --bind 0.0.0.0:$PORT
    env:
      - key: DJANGO_SETTINGS_MODULE
        value: "your_project_name.settings"
